/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TicTacToi;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class TicTacToi extends javax.swing.JFrame {

    int turn=2;
    int btnused[]={0,0,0,0,0,0,0,0,0};
    
    int p1won[]={0,0,0,0,0,0,0,0,0};
    int p2won[]={0,0,0,0,0,0,0,0,0};
    
    int p1won()
    {
        if(p1won[0]==1 && p1won[1]==1 && p1won[2]==1)
        {
            return 1;
        }
        if(p1won[3]==1 && p1won[4]==1 && p1won[5]==1)
        {
            return 1;
        }
        if(p1won[6]==1 && p1won[7]==1 && p1won[8]==1)
        {
            return 1;
        }
        if(p1won[0]==1 && p1won[3]==1 && p1won[6]==1)
        {
            return 1;
        }
        if(p1won[1]==1 && p1won[4]==1 && p1won[7]==1)
        {
            return 1;
        }
        if(p1won[2]==1 && p1won[5]==1 && p1won[8]==1)
        {
            return 1;
        }
        if(p1won[2]==1 && p1won[4]==1 && p1won[6]==1)
        {
            return 1;
        }
        if(p1won[0]==1 && p1won[4]==1 && p1won[8]==1)
        {
            return 1;
        }
        return 0;
    }
    
    int p2won()
    {
        if(p2won[0]==1 && p2won[1]==1 && p2won[2]==1)
        {
            return 1;
        }
        if(p2won[3]==1 && p2won[4]==1 && p2won[5]==1)
        {
            return 1;
        }
        if(p2won[6]==1 && p2won[7]==1 && p2won[8]==1)
        {
            return 1;
        }
        if(p2won[0]==1 && p2won[3]==1 && p2won[6]==1)
        {
            return 1;
        }
        if(p2won[1]==1 && p2won[4]==1 && p2won[7]==1)
        {
            return 1;
        }
        if(p2won[2]==1 && p2won[5]==1 && p2won[8]==1)
        {
            return 1;
        }
        if(p2won[2]==1 && p2won[4]==1 && p2won[6]==1)
        {
            return 1;
        }
        if(p2won[0]==1 && p2won[4]==1 && p2won[8]==1)
        {
            return 1;
        }
        return 0;
    }
    
    public TicTacToi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reset = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        reset.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        reset.setText("Play Again");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Tic Tac Toi");

        exit.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
       if(btnused[2]==0)
        {
             if(turn%2==0)
             {
                 turn++;
                 b3.setText("X");
                 btnused[2]=1;
                 p1won[2]=1;
                 
                 int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
            else
            {
                turn++;
                b3.setText("O");
                btnused[2]=1;
                p2won[2]=1;
                
                int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "This Button is used Already");
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if(btnused[8]==0)
        {
             if(turn%2==0)
             {
                 turn++;
                 b9.setText("X");
                 btnused[8]=1;
                 p1won[8]=1;
                 
                 int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
            else
            {
                turn++;
                b9.setText("O");
                btnused[8]=1;
                p2won[8]=1;
                
                int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "This Button is used Already");
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(btnused[0]==0)
        {
             if(turn%2==0)
             {
                 turn++;
                 b1.setText("X");
                 btnused[0]=1;
                 p1won[0]=1;
                 
                 int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
            else
            {
                turn++;
                b1.setText("O");
                btnused[0]=1;
                p2won[0]=1;
                
                int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "This Button is used Already");
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(btnused[1]==0)
        {
             if(turn%2==0)
             {
                 turn++;
                 b2.setText("X");
                 btnused[1]=1;
                 p1won[1]=1;
                 
                 int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
            else
            {
                turn++;
                b2.setText("O");
                btnused[1]=1;
                p2won[1]=1;
                
                int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "This Button is used Already");
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
         if(btnused[3]==0)
        {
             if(turn%2==0)
             {
                 turn++;
                 b4.setText("X");
                 btnused[3]=1;
                 p1won[3]=1;
                 
                 int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
            else
            {
                turn++;
                b4.setText("O");
                btnused[3]=1;
                p2won[3]=1;
                
                int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "This Button is used Already");
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
         if(btnused[4]==0)
        {
             if(turn%2==0)
             {
                 turn++;
                 b5.setText("X");
                 btnused[4]=1;
                 p1won[4]=1;
                 
                 int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
            else
            {
                turn++;
                b5.setText("O");
                btnused[4]=1;
                p2won[4]=1;
                
                int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "This Button is used Already");
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if(btnused[5]==0)
        {
             if(turn%2==0)
             {
                 turn++;
                 b6.setText("X");
                 btnused[5]=1;
                 p1won[5]=1;
                 
                 int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
            else
            {
                turn++;
                b6.setText("O");
                btnused[5]=1;
                p2won[5]=1;
                
                int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "This Button is used Already");
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if(btnused[6]==0)
        {
             if(turn%2==0)
             {
                 turn++;
                 b7.setText("X");
                 btnused[6]=1;
                 p1won[6]=1;
                 
                 int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
            else
            {
                turn++;
                b7.setText("O");
                btnused[6]=1;
                p2won[6]=1;
                
                int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "This Button is used Already");
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
         if(btnused[7]==0)
        {
             if(turn%2==0)
             {
                 turn++;
                 b8.setText("X");
                 btnused[7]=1;
                 p1won[7]=1;
                 
                 int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
            else
            {
                turn++;
                b8.setText("O");
                btnused[7]=1;
                p2won[7]=1;
                
                int result1=p1won();
                 int result2=p2won();
                 
                 if(result1==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player X has Won ***");
                 }
                 else if(result2==1)
                 {
                     JOptionPane.showMessageDialog(rootPane, "*** Player O has Won ***");
                     
                 }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "This Button is used Already");
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
        
        turn=2;
        
        for(int i=0;i<9;i++)
        {
            btnused[i]=0;
        }
        for(int i=0;i<9;i++)
        {
            p1won[i]=0;
        }
        for(int i=0;i<9;i++)
        {
            p2won[i]=0;
        }
        
    }//GEN-LAST:event_resetActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
